//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ORGINATION
    {
        public int ORG_ID { get; set; }
        public string ORGNAME { get; set; }
        public string ORG_AVBRIVATION { get; set; }
        public string ORG_ADDRESS { get; set; }
        public string ORG_PHONE { get; set; }
        public string ORG_LOCATION { get; set; }
        public string ORG_LOGO { get; set; }
        public string ORG_VISSION { get; set; }
        public string ORG_EMAIL { get; set; }
        public string ORG_A { get; set; }
        public string ORG_B { get; set; }
        public string ORG_C { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_BARCH { get; set; }
        public string ORG_HEAD { get; set; }
    }
}
