//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_R_RECEIPT
    {
        public int R_ID { get; set; }
        public Nullable<System.DateTime> RCPT_DATE { get; set; }
        public Nullable<int> HPTL_ID { get; set; }
        public Nullable<int> DEPT_ID { get; set; }
        public Nullable<int> MR_NO { get; set; }
        public Nullable<int> TEEATMNT_ID { get; set; }
        public Nullable<int> CONSULTANT_ID { get; set; }
        public Nullable<int> PAYMENT_ID { get; set; }
        public Nullable<int> PAYMENT_AMOUNT { get; set; }
        public Nullable<int> R_LOGIC_ID { get; set; }
        public Nullable<System.DateTime> R_LOGIC_DATE { get; set; }
        public Nullable<int> HPTL { get; set; }
        public Nullable<int> P_TYPE { get; set; }
        public Nullable<int> USER_PR { get; set; }
        public Nullable<int> MAG_PR { get; set; }
        public Nullable<int> PANEL { get; set; }
        public Nullable<int> PANEL_FEE { get; set; }
        public Nullable<int> CONST_TYPE { get; set; }
        public Nullable<int> PAID_YN { get; set; }
        public Nullable<int> SHARE_AMOUNT { get; set; }
        public Nullable<int> TOKEN { get; set; }
        public Nullable<System.DateTime> PAY_DATE { get; set; }
        public Nullable<int> APP_YN { get; set; }
        public Nullable<System.DateTime> APP_DATE { get; set; }
        public Nullable<int> APP_FEE { get; set; }
        public Nullable<int> APP_TOKEN { get; set; }
        public Nullable<System.DateTime> APP_TIME { get; set; }
    
        public virtual TBL_R_DEPT TBL_R_DEPT { get; set; }
        public virtual TBL_R_PATIENT TBL_R_PATIENT { get; set; }
        public virtual TBL_CONSULTANT TBL_CONSULTANT { get; set; }
    }
}
