//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_R_TEST
    {
        public int TEST_ID { get; set; }
        public Nullable<System.DateTime> TEST_DATE { get; set; }
        public Nullable<int> MR_NO { get; set; }
        public Nullable<int> DISC_ID { get; set; }
        public Nullable<int> DISC_AMOUNT { get; set; }
        public Nullable<int> GRANT_TOTAL { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<System.DateTime> USER_DATE { get; set; }
        public Nullable<int> REFUND_AMOUNT { get; set; }
        public Nullable<System.DateTime> REF_DATE { get; set; }
        public Nullable<int> CONST_ID { get; set; }
        public Nullable<int> USER_PR { get; set; }
        public Nullable<int> MAG_PR { get; set; }
        public Nullable<int> PANEL { get; set; }
        public Nullable<int> DC_REFUND { get; set; }
        public Nullable<int> COMFRM { get; set; }
        public Nullable<int> SHIFT_ID { get; set; }
        public Nullable<int> IPD_AMOUNT { get; set; }
        public Nullable<int> IPD_NO { get; set; }
        public Nullable<int> SAMLEYN { get; set; }
        public Nullable<int> LAB_NO { get; set; }
        public Nullable<int> GRANT_TOTALP { get; set; }
    
        public virtual TBL_USER_D TBL_USER_D { get; set; }
    }
}
