//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_D
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_USER_D()
        {
            this.TBL_R_TEST = new HashSet<TBL_R_TEST>();
        }
    
        public int USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public Nullable<int> DEP_CODE { get; set; }
        public Nullable<int> CMP_CODE { get; set; }
        public string USERS { get; set; }
        public Nullable<int> MAG_ACT { get; set; }
        public Nullable<int> R_ACTIVE { get; set; }
        public Nullable<int> ORG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_R_TEST> TBL_R_TEST { get; set; }
    }
}
