//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_R_DEPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_R_DEPT()
        {
            this.TBL_CONSULTANT = new HashSet<TBL_CONSULTANT>();
            this.TBL_R_RECEIPT = new HashSet<TBL_R_RECEIPT>();
        }
    
        public int DEPT_ID { get; set; }
        public string DEPT_NAME { get; set; }
        public Nullable<int> PRY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CONSULTANT> TBL_CONSULTANT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_R_RECEIPT> TBL_R_RECEIPT { get; set; }
    }
}
