//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Visit
    {
        public int CON_JOB_ID { get; set; }
        public string CON_NAME { get; set; }
        public Nullable<int> CON_FEE { get; set; }
        public Nullable<int> CD { get; set; }
        public Nullable<int> CTFEE { get; set; }
        public string DEGREE { get; set; }
        public Nullable<int> ER_FEE { get; set; }
        public Nullable<int> SP_VISIT { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> FELLOW_UP { get; set; }
        public string DESG { get; set; }
        public Nullable<int> DOC_SHARE { get; set; }
        public Nullable<int> DEP_ID { get; set; }
        public int R_ID { get; set; }
        public Nullable<System.DateTime> RCPT_DATE { get; set; }
        public Nullable<int> HPTL_ID { get; set; }
        public Nullable<int> DEPT_ID { get; set; }
        public Nullable<int> MR_NO { get; set; }
        public Nullable<int> TEEATMNT_ID { get; set; }
        public Nullable<int> CONSULTANT_ID { get; set; }
        public Nullable<int> PAYMENT_ID { get; set; }
        public Nullable<int> PAYMENT_AMOUNT { get; set; }
        public Nullable<int> R_LOGIC_ID { get; set; }
        public Nullable<System.DateTime> R_LOGIC_DATE { get; set; }
        public Nullable<int> HPTL { get; set; }
        public Nullable<int> P_TYPE { get; set; }
        public Nullable<int> USER_PR { get; set; }
        public Nullable<int> MAG_PR { get; set; }
        public Nullable<int> PANEL { get; set; }
        public Nullable<int> PANEL_FEE { get; set; }
        public Nullable<int> CONST_TYPE { get; set; }
        public Nullable<int> PAID_YN { get; set; }
        public Nullable<int> SHARE_AMOUNT { get; set; }
        public Nullable<int> TOKEN { get; set; }
        public Nullable<System.DateTime> PAY_DATE { get; set; }
        public Nullable<int> APP_YN { get; set; }
        public Nullable<System.DateTime> APP_DATE { get; set; }
        public Nullable<int> APP_FEE { get; set; }
        public Nullable<int> APP_TOKEN { get; set; }
        public Nullable<System.DateTime> APP_TIME { get; set; }
        public Nullable<int> FAMILY_NO { get; set; }
        public Nullable<System.DateTime> TDATE { get; set; }
        public int Expr1 { get; set; }
        public Nullable<int> AGE { get; set; }
        public string FIRST_NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string STREET_ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public Nullable<int> POSTAL_CODE { get; set; }
        public Nullable<int> PHONE_NUMBER1 { get; set; }
        public Nullable<int> PHONE_NUMBER2 { get; set; }
        public Nullable<int> CREDIT_LIMIT { get; set; }
        public string EMAIL { get; set; }
        public string GENDER { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> ADMINTOTAL { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public string F_NAME { get; set; }
        public Nullable<int> PANEL_G { get; set; }
        public Nullable<int> ADDMISSIONID { get; set; }
        public Nullable<int> PMNHP_NO { get; set; }
        public string PROCEDUREGROUP { get; set; }
        public Nullable<int> PATIENTTYPE { get; set; }
        public Nullable<int> PROTOTAL { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public Nullable<int> NIC { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH { get; set; }
        public string SSN { get; set; }
        public string EMG_NAME { get; set; }
        public Nullable<int> EMG_CONTACT { get; set; }
        public string EMG_RELATION { get; set; }
        public Nullable<int> EMG_HOME { get; set; }
        public Nullable<int> EMP_CODE { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_DESG { get; set; }
        public Nullable<int> EMP_CONTACT { get; set; }
        public Nullable<int> EMP_DEPART { get; set; }
        public string EMP_ADDRESS { get; set; }
        public Nullable<int> POLICY_ID { get; set; }
        public Nullable<System.DateTime> EFFECT_DATE { get; set; }
        public string P_GROUP { get; set; }
        public string P_HOLDER_NAME { get; set; }
        public Nullable<System.DateTime> P_DOB { get; set; }
        public string P_RELATION { get; set; }
        public string P_INSSURANCE { get; set; }
        public int Expr4 { get; set; }
        public string DEPT_NAME { get; set; }
        public Nullable<int> PRY { get; set; }
        public string TEL_NO { get; set; }
        public string CNIC_NO { get; set; }
    }
}
